sbp_version: 4
mbp_version: null

data_dir: "/data/astro/scratch/lcabayol/NFphotoz/data/CFHT_sims_v3"
photometry_type: 'MBP'

multiple_exposures: True
nexp: 3
zp_calib: True
zp_calib_err: 2
verbose: true
output_model: "/nfs/pic.es/user/l/lcabayol/AI/Flow4z/models/CFHT_MBP_mexp_v3.pt"
file_type: "features"
predict_photoz: False
ntransformation: 8
bands: 
  - 'CFHT_U'
  - 'CFHT_G'
  - 'CFHT_R'
  - 'CFHT_I'
  - 'CFHT_Z'

# Dictionary of hyperparameters
hyperparams:
  batch_size: 100         # Number of samples per batch during training
  nepochs: 600             # Number of training epochs
  learning_rate: 0.001    # Learning rate for the optimizer