sbp_version: 2
mbp_version: 1
restore: False

data_dir: "/data/astro/scratch/lcabayol/NFphotoz/data/PAUS_sims_v3_zarr.zarr/features_v2.zarr"
metadata_dir: "/data/astro/scratch/lcabayol/NFphotoz/data/PAUS_sims_metadata+_v3_zarr.zarr"
photometry_type: 'MBP'

multiple_exposures: True
nexp: 3
zp_calib: 2
verbose: true
output_model: "/nfs/pic.es/user/l/lcabayol/AI/Flow4z/models/PAUS_MBP_mexp_v3.pt"
file_type: "features"
predict_photoz: False
ntransformation: 8
# bands: 
#   - 'CFHT_U'
#   - 'CFHT_G'
#   - 'CFHT_R'
#   - 'CFHT_I'
#   - 'CFHT_Z'

bands: 
    - 'nb455'
    - 'nb465'
    - 'nb475'
    - 'nb485'
    - 'nb495'
    - 'nb505'
    - 'nb515'
    - 'nb525'
    - 'nb535'
    - 'nb545'
    - 'nb555'
    - 'nb565'
    - 'nb575'
    - 'nb585'
    - 'nb595'
    - 'nb605'
    - 'nb615'
    - 'nb625'
    - 'nb635'
    - 'nb645'
    - 'nb655'
    - 'nb665'
    - 'nb675'
    - 'nb685'
    - 'nb695'
    - 'nb705'
    - 'nb715'
    - 'nb725'
    - 'nb735'
    - 'nb745'
    - 'nb755'
    - 'nb765'
    - 'nb775'
    - 'nb785'
    - 'nb795'
    - 'nb805'
    - 'nb815'
    - 'nb825'
    - 'nb835'
    - 'nb845'


# Dictionary of hyperparameters
hyperparams:
  batch_size: 100         # Number of samples per batch during training
  nepochs: 1000             # Number of training epochs
  learning_rate: 0.001    # Learning rate for the optimizer